-- 004_donation_model.sql
-- Donation model: no payment step. Sharers donate swipes for free.
-- mark_ordered now transitions directly from 'accepted' → 'ordered'.
-- This migration is kept for documentation but the logic is now
-- baked into 003_rpc_functions.sql directly.
